In [148]:
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import mean_absolute_error

# I merged the test set to my train set previously on excel

In [2]:
df_fc = pd.read_csv('C:/Users/shrut/Documents/Shruti admin/Canada 1/QU/Module 3/Predictive Modelling/92422_214915_bundle_archive/fulfilment_center_info.csv')
df_meal = pd.read_csv('C:/Users/shrut/Documents/Shruti admin/Canada 1/QU/Module 3/Predictive Modelling/92422_214915_bundle_archive/meal_info.csv')
df_train = pd.read_csv('C:/Users/shrut/Documents/Shruti admin/Canada 1/QU/Module 3/Predictive Modelling/92422_214915_bundle_archive/train.csv')

In [3]:
#merging the datasets df_fc and df_meal to df_train and df_test using the meal_id and center_id
df_train = pd.merge(df_train, df_fc,
                    how="left",
                    left_on='center_id',
                    right_on='center_id')

df_train = pd.merge(df_train, df_meal,
                    how='left',
                    left_on='meal_id',
                    right_on='meal_id')

In [4]:
df_train.head()
df_train.tail()

id  week  center_id  meal_id  checkout_price  base_price  \
489116  1250239   155         61     1543          482.09      484.09   
489117  1039516   155         61     2304          483.09      483.09   
489118  1158107   155         61     2664          322.07      323.07   
489119  1444235   155         61     2569          322.07      323.07   
489120  1291286   155         61     2490          276.45      276.45   

        emailer_for_promotion  homepage_featured  num_orders  city_code  \
489116                      0                  0         NaN        473   
489117                      0                  0         NaN        473   
489118                      0                  0         NaN        473   
489119                      0                  0         NaN        473   
489120                      0                  0         NaN        473   

        region_code center_type  op_area category  cuisine  
489116           77      TYPE_A      4.5   Desert   Indian  
489117           77      TYPE_A      4.5   Desert   Indian  
489118           77      TYPE_A      4.5    Salad  Italian  
489119           77      TYPE_A      4.5    Salad  Italian  
489120           77      TYPE_A      4.5    Salad  Italian

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 489121 entries, 0 to 489120
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   id                     489121 non-null  int64  
 1   week                   489121 non-null  int64  
 2   center_id              489121 non-null  int64  
 3   meal_id                489121 non-null  int64  
 4   checkout_price         489121 non-null  float64
 5   base_price             489121 non-null  float64
 6   emailer_for_promotion  489121 non-null  int64  
 7   homepage_featured      489121 non-null  int64  
 8   num_orders             456548 non-null  float64
 9   city_code              489121 non-null  int64  
 10  region_code            489121 non-null  int64  
 11  center_type            489121 non-null  object 
 12  op_area                489121 non-null  float64
 13  category               489121 non-null  object 
 14  cuisine                489121 non-nu

In [6]:
#one-hot encoding
df_train = pd.get_dummies(df_train, columns = df_train.select_dtypes(exclude=['int64','float64']).columns, drop_first = True)

In [7]:
df_train.head()
df_train.tail()

id  week  center_id  meal_id  checkout_price  base_price  \
489116  1250239   155         61     1543          482.09      484.09   
489117  1039516   155         61     2304          483.09      483.09   
489118  1158107   155         61     2664          322.07      323.07   
489119  1444235   155         61     2569          322.07      323.07   
489120  1291286   155         61     2490          276.45      276.45   

        emailer_for_promotion  homepage_featured  num_orders  city_code  ...  \
489116                      0                  0         NaN        473  ...   
489117                      0                  0         NaN        473  ...   
489118                      0                  0         NaN        473  ...   
489119                      0                  0         NaN        473  ...   
489120                      0                  0         NaN        473  ...   

        category_Pizza  category_Rice Bowl  category_Salad  category_Sandwich  \
489116               0                   0               0                  0   
489117               0                   0               0                  0   
489118               0                   0               1                  0   
489119               0                   0               1                  0   
489120               0                   0               1                  0   

        category_Seafood  category_Soup  category_Starters  cuisine_Indian  \
489116                 0              0                  0               1   
489117                 0              0                  0               1   
489118                 0              0                  0               0   
489119                 0              0                  0               0   
489120                 0              0                  0               0   

        cuisine_Italian  cuisine_Thai  
489116                0             0  
489117                0             0  
489118                1             0  
489119                1             0  
489120                1             0  

[5 rows x 30 columns]

In [8]:
pd.DataFrame(df_train).isna().sum()

id                           0
week                         0
center_id                    0
meal_id                      0
checkout_price               0
base_price                   0
emailer_for_promotion        0
homepage_featured            0
num_orders               32573
city_code                    0
region_code                  0
op_area                      0
center_type_TYPE_B           0
center_type_TYPE_C           0
category_Biryani             0
category_Desert              0
category_Extras              0
category_Fish                0
category_Other Snacks        0
category_Pasta               0
category_Pizza               0
category_Rice Bowl           0
category_Salad               0
category_Sandwich            0
category_Seafood             0
category_Soup                0
category_Starters            0
cuisine_Indian               0
cuisine_Italian              0
cuisine_Thai                 0
dtype: int64

In [9]:
df_train["num_orders"] = df_train["num_orders"].fillna(0)

In [10]:
df_train.info()
df_train.tail()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 489121 entries, 0 to 489120
Data columns (total 30 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   id                     489121 non-null  int64  
 1   week                   489121 non-null  int64  
 2   center_id              489121 non-null  int64  
 3   meal_id                489121 non-null  int64  
 4   checkout_price         489121 non-null  float64
 5   base_price             489121 non-null  float64
 6   emailer_for_promotion  489121 non-null  int64  
 7   homepage_featured      489121 non-null  int64  
 8   num_orders             489121 non-null  float64
 9   city_code              489121 non-null  int64  
 10  region_code            489121 non-null  int64  
 11  op_area                489121 non-null  float64
 12  center_type_TYPE_B     489121 non-null  uint8  
 13  center_type_TYPE_C     489121 non-null  uint8  
 14  category_Biryani       489121 non-nu

id  week  center_id  meal_id  checkout_price  base_price  \
489116  1250239   155         61     1543          482.09      484.09   
489117  1039516   155         61     2304          483.09      483.09   
489118  1158107   155         61     2664          322.07      323.07   
489119  1444235   155         61     2569          322.07      323.07   
489120  1291286   155         61     2490          276.45      276.45   

        emailer_for_promotion  homepage_featured  num_orders  city_code  ...  \
489116                      0                  0         0.0        473  ...   
489117                      0                  0         0.0        473  ...   
489118                      0                  0         0.0        473  ...   
489119                      0                  0         0.0        473  ...   
489120                      0                  0         0.0        473  ...   

        category_Pizza  category_Rice Bowl  category_Salad  category_Sandwich  \
489116               0                   0               0                  0   
489117               0                   0               0                  0   
489118               0                   0               1                  0   
489119               0                   0               1                  0   
489120               0                   0               1                  0   

        category_Seafood  category_Soup  category_Starters  cuisine_Indian  \
489116                 0              0                  0               1   
489117                 0              0                  0               1   
489118                 0              0                  0               0   
489119                 0              0                  0               0   
489120                 0              0                  0               0   

        cuisine_Italian  cuisine_Thai  
489116                0             0  
489117                0             0  
489118                1             0  
489119                1             0  
489120                1             0  

[5 rows x 30 columns]

In [11]:
pd.DataFrame(df_train).isna().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
city_code                0
region_code              0
op_area                  0
center_type_TYPE_B       0
center_type_TYPE_C       0
category_Biryani         0
category_Desert          0
category_Extras          0
category_Fish            0
category_Other Snacks    0
category_Pasta           0
category_Pizza           0
category_Rice Bowl       0
category_Salad           0
category_Sandwich        0
category_Seafood         0
category_Soup            0
category_Starters        0
cuisine_Indian           0
cuisine_Italian          0
cuisine_Thai             0
dtype: int64

In [12]:
train = df_train[df_train['week'] <= 145].copy()

In [13]:
y = train['num_orders']
X = train.drop(['id', 'num_orders'], axis=1)

In [14]:
X.tail()
y.tail()

456543     68.0
456544     42.0
456545    501.0
456546    729.0
456547    162.0
Name: num_orders, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state=42)

# Linear Regression Model

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
Y_Pred = regressor.predict(X_test)
Y_Pred

array([-4.65661681e-01,  3.81012651e+02,  2.25821331e+02, ...,
        5.39710466e+02,  1.01178137e+02,  4.39807152e+02])

In [18]:
X_test

week  center_id  meal_id  checkout_price  base_price  \
203536    68        177     1962          639.23      641.23   
301801    98         29     2707          177.57      177.57   
254032    84         83     2640          282.33      280.33   
339158   110        124     2304          474.39      474.39   
3203       2         52     2539          133.92      133.92   
...      ...        ...      ...             ...         ...   
95283     33         50     1525          292.03      292.03   
282522    92         10     1885          144.56      144.56   
195794    65         61     2539          119.34      118.34   
446517   142         86     2640          320.13      321.13   
302061    98         88     1754          292.03      291.03   

        emailer_for_promotion  homepage_featured  city_code  region_code  \
203536                      0                  0        683           56   
301801                      0                  0        526           34   
254032                      0                  0        659           77   
339158                      0                  0        590           56   
3203                        0                  0        685           56   
...                       ...                ...        ...          ...   
95283                       0                  0        556           77   
282522                      0                  0        590           56   
195794                      0                  0        473           77   
446517                      0                  0        699           85   
302061                      0                  0        526           34   

        op_area  ...  category_Pizza  category_Rice Bowl  category_Salad  \
203536      3.4  ...               1                   0               0   
301801      4.0  ...               0                   0               0   
254032      5.3  ...               0                   0               0   
339158      4.0  ...               0                   0               0   
3203        5.6  ...               0                   0               0   
...         ...  ...             ...                 ...             ...   
95283       4.8  ...               0                   0               0   
282522      6.3  ...               0                   0               0   
195794      4.5  ...               0                   0               0   
446517      4.0  ...               0                   0               0   
302061      4.1  ...               0                   0               0   

        category_Sandwich  category_Seafood  category_Soup  category_Starters  \
203536                  0                 0              0                  0   
301801                  0                 0              0                  0   
254032                  0                 0              0                  1   
339158                  0                 0              0                  0   
3203                    0                 0              0                  0   
...                   ...               ...            ...                ...   
95283                   0                 0              0                  0   
282522                  0                 0              0                  0   
195794                  0                 0              0                  0   
446517                  0                 0              0                  1   
302061                  1                 0              0                  0   

        cuisine_Indian  cuisine_Italian  cuisine_Thai  
203536               0                0             0  
301801               0                1             0  
254032               0                0             1  
339158               1                0             0  
3203                 0                0             1  
...                ...              ...           ...  
95283                0                0         

In [19]:
dataset=pd.DataFrame({'Actual':y_test, 'Predicted':Y_Pred})
dataset

Actual   Predicted
203536    28.0   -0.465662
301801   176.0  381.012651
254032   391.0  225.821331
339158    14.0  -46.692512
3203     405.0  647.828491
...        ...         ...
95283    136.0  160.243530
282522  1608.0  671.644797
195794   406.0  539.710466
446517    82.0  101.178137
302061   405.0  439.807152

[91310 rows x 2 columns]

In [150]:
MAE_lr = metrics.mean_absolute_error(y_test, Y_Pred)
MAE_lr

161.33298200795033

# Decision Tree Regressor 

In [21]:
from sklearn.tree import DecisionTreeRegressor

In [22]:
DecisionTreeRegModel = DecisionTreeRegressor()

In [23]:
DecisionTreeRegModel.fit(X_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [24]:
y_preddt = DecisionTreeRegModel.predict(X_test)

In [25]:
dt_dataset = pd.DataFrame({'Actual':y_test, 'Predicted':y_preddt})
dt_dataset

Actual  Predicted
203536    28.0       81.0
301801   176.0      271.0
254032   391.0      284.0
339158    14.0       26.0
3203     405.0      393.0
...        ...        ...
95283    136.0      150.0
282522  1608.0     1322.0
195794   406.0      284.0
446517    82.0       67.0
302061   405.0      378.0

[91310 rows x 2 columns]

In [152]:
MAE_dt = metrics.mean_absolute_error(y_test, y_preddt)
MAE_dt

89.58740554156171

In [153]:
MASE = MAE_dt/MAE_lr 
MASE

0.5552950452322696

# cross validation

In [58]:
train1 = df_train[df_train['week'] <= 145].copy()

In [59]:
y1 = train1[(train1['week'] >= 126) & (train1['week'] <= 135)]
test_actual1 = y1[['num_orders']]
y1 = y1.drop(['id', 'num_orders'], axis=1)

In [60]:
x1 = train1[(train1['week'] <= 125) | (train1['week'] >= 136)]
train_actual1 = x1[['num_orders']]
x1 = x1.drop(['id', 'num_orders'], axis=1)

In [61]:
DecisionTreeRegModel.fit(x1,train_actual1)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [62]:
y_orders1 = DecisionTreeRegModel.predict(y1)
y_orders1

array([229., 202., 270., ..., 107., 527., 215.])

In [155]:
MAE_fold1 = metrics.mean_absolute_error(test_actual1, y_orders1)
MAE_fold1

101.77227300426568

In [158]:
MASE_fold1 = MAE_fold1/MAE_lr 
MASE_fold1

0.6308212476928645

In [78]:
y2 = train1[(train1['week'] >= 127) & (train1['week'] <= 136)]
test_actual2 = y2[['num_orders']]
y2 = y2.drop(['id', 'num_orders'], axis=1)

In [79]:
x2 = train1[(train1['week'] <= 126) | (train1['week'] >= 137)]
train_actual2 = x2[['num_orders']]
x2 = x2.drop(['id', 'num_orders'], axis=1)

In [80]:
DecisionTreeRegModel.fit(x2,train_actual2)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [81]:
y_orders2 = DecisionTreeRegModel.predict(y2)
y_orders2

array([123., 109., 108., ..., 109., 432., 339.])

In [156]:
MAE_fold2 = metrics.mean_absolute_error(test_actual2, y_orders2)
MAE_fold2

107.01683973324401

In [160]:
MASE_fold2 = MAE_fold2/MAE_lr 
MASE_fold2

0.663328963497187

In [83]:
y3 = train1[(train1['week'] >= 128) & (train1['week'] <= 137)]
test_actual3 = y3[['num_orders']]
y3 = y3.drop(['id', 'num_orders'], axis=1)

x3 = train1[(train1['week'] <= 127) | (train1['week'] >= 138)]
train_actual3 = x3[['num_orders']]
x3 = x3.drop(['id', 'num_orders'], axis=1)

In [84]:
DecisionTreeRegModel.fit(x3,train_actual3)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [85]:
y_orders3 = DecisionTreeRegModel.predict(y3)
y_orders3

array([ 67., 163., 163., ..., 512., 310., 162.])

In [157]:
MAE_fold3 = metrics.mean_absolute_error(test_actual3, y_orders3)
MAE_fold3

106.28265433413455

In [161]:
MASE_fold3 = MAE_fold3/MAE_lr 
MASE_fold3

0.6587782176424225

In [87]:
y4 = train1[(train1['week'] >= 129) & (train1['week'] <= 138)]
test_actual4 = y4[['num_orders']]
y4 = y4.drop(['id', 'num_orders'], axis=1)

x4 = train1[(train1['week'] <= 128) | (train1['week'] >= 139)]
train_actual4 = x4[['num_orders']]
x4 = x4.drop(['id', 'num_orders'], axis=1)

In [88]:
DecisionTreeRegModel.fit(x4,train_actual4)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [89]:
y_orders4 = DecisionTreeRegModel.predict(y4)
y_orders4

array([107., 136., 134., ..., 366., 284., 217.])

In [163]:
MAE_fold4 = metrics.mean_absolute_error(test_actual4, y_orders4)
MAE_fold4

106.12368028721818

In [164]:
MASE_fold4 = MAE_fold4/MAE_lr 
MASE_fold4

0.6577928391727644

In [95]:
y5 = train1[(train1['week'] >= 130) & (train1['week'] <= 139)]
test_actual5 = y5[['num_orders']]
y5 = y5.drop(['id', 'num_orders'], axis=1)

x5 = train1[(train1['week'] <= 129) | (train1['week'] >= 140)]
train_actual5 = x5[['num_orders']]
x5 = x5.drop(['id', 'num_orders'], axis=1)

In [96]:
DecisionTreeRegModel.fit(x5,train_actual5)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [97]:
y_orders5 = DecisionTreeRegModel.predict(y5)
y_orders5

array([ 40., 121., 136., ..., 310., 310., 162.])

In [165]:
MAE_fold5 = metrics.mean_absolute_error(test_actual5, y_orders5)
MAE_fold5

101.81582711915995

In [166]:
MASE_fold5 = MAE_fold5/MAE_lr 
MASE_fold5

0.6310912118028201

In [99]:
y6 = train1[(train1['week'] >= 131) & (train1['week'] <= 140)]
test_actual6 = y6[['num_orders']]
y6 = y6.drop(['id', 'num_orders'], axis=1)

x6 = train1[(train1['week'] <= 130) | (train1['week'] >= 141)]
train_actual6 = x6[['num_orders']]
x6 = x6.drop(['id', 'num_orders'], axis=1)

In [100]:
DecisionTreeRegModel.fit(x6,train_actual6)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [101]:
y_orders6 = DecisionTreeRegModel.predict(y6)
y_orders6

array([121., 107.,  94., ..., 203., 271., 635.])

In [167]:
MAE_fold6 = metrics.mean_absolute_error(test_actual6, y_orders6)
MAE_fold6

96.38415985909077

In [168]:
MASE_fold6 = MAE_fold6/MAE_lr 
MASE_fold6

0.5974237794373692

In [103]:
y7 = train1[(train1['week'] >= 132) & (train1['week'] <= 141)]
test_actual7 = y7[['num_orders']]
y7 = y7.drop(['id', 'num_orders'], axis=1)

x7 = train1[(train1['week'] <= 131) | (train1['week'] >= 142)]
train_actual7 = x7[['num_orders']]
x7 = x7.drop(['id', 'num_orders'], axis=1)

In [104]:
DecisionTreeRegModel.fit(x7,train_actual7)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [105]:
y_orders7 = DecisionTreeRegModel.predict(y7)
y_orders7

array([ 95., 188., 202., ..., 391., 447., 190.])

In [169]:
MAE_fold7 = metrics.mean_absolute_error(test_actual7, y_orders7)
MAE_fold7

93.66910848354053

In [170]:
MASE_fold7 = MAE_fold7/MAE_lr 
MASE_fold7

0.5805949119500228

In [107]:
y8 = train1[(train1['week'] >= 133) & (train1['week'] <= 142)]
test_actual8 = y8[['num_orders']]
y8 = y8.drop(['id', 'num_orders'], axis=1)

x8 = train1[(train1['week'] <= 132) | (train1['week'] >= 143)]
train_actual8 = x8[['num_orders']]
x8 = x8.drop(['id', 'num_orders'], axis=1)

In [108]:
DecisionTreeRegModel.fit(x8,train_actual8)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [109]:
y_orders8 = DecisionTreeRegModel.predict(y8)
y_orders8

array([ 94., 337., 108., ..., 391., 447., 190.])

In [171]:
MAE_fold8 = metrics.mean_absolute_error(test_actual8, y_orders8)
MAE_fold8

91.67408173823073

In [172]:
MASE_fold8 = MAE_fold8/MAE_lr 
MASE_fold8

0.5682290167655434

In [111]:
y9 = train1[(train1['week'] >= 134) & (train1['week'] <= 143)]
test_actual9 = y9[['num_orders']]
y9 = y9.drop(['id', 'num_orders'], axis=1)

x9 = train1[(train1['week'] <= 133) | (train1['week'] >= 144)]
train_actual9 = x9[['num_orders']]
x9 = x9.drop(['id', 'num_orders'], axis=1)

In [112]:
DecisionTreeRegModel.fit(x9,train_actual9)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [113]:
y_orders9 = DecisionTreeRegModel.predict(y9)
y_orders9

array([162., 188., 162., ..., 339., 271., 190.])

In [173]:
MAE_fold9 = metrics.mean_absolute_error(test_actual9, y_orders9)
MAE_fold9

88.36002679495768

In [174]:
MASE_fold9 = MAE_fold9/MAE_lr 
MASE_fold9

0.5476873091616404

In [115]:
y10 = train1[(train1['week'] >= 135) & (train1['week'] <= 144)]
test_actual10 = y10[['num_orders']]
y10 = y10.drop(['id', 'num_orders'], axis=1)

x10 = train1[(train1['week'] <= 134) | (train1['week'] == 145)]
train_actual10 = x10[['num_orders']]
x10 = x10.drop(['id', 'num_orders'], axis=1)

In [116]:
DecisionTreeRegModel.fit(x10,train_actual10)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [117]:
y_orders10 = DecisionTreeRegModel.predict(y10)
y_orders10

array([ 94., 176.,  80., ..., 338., 339., 149.])

In [175]:
MAE_fold10 = metrics.mean_absolute_error(test_actual10, y_orders10)
MAE_fold10

91.65155116718473

In [176]:
MASE_fold10 = MAE_fold10/MAE_lr 
MASE_fold10

0.568089364161559

# MASE table

In [181]:
MASE_table = pd.DataFrame({'Id':['MASE_fold1','MASE_fold2','MASE_fold3', 'MASE_fold4', 'MASE_fold5', 'MASE_fold6', 'MASE_fold7', 'MASE_fold8', 'MASE_fold9', 'MASE_fold10', 'Average'],
                          'MASE':[0.63082,0.66332,0.65877,0.65779,0.63109,0.59742,0.58059,0.56822,0.54768,0.56808,0.61037]})
MASE_table

Id     MASE
0    MASE_fold1  0.63082
1    MASE_fold2  0.66332
2    MASE_fold3  0.65877
3    MASE_fold4  0.65779
4    MASE_fold5  0.63109
5    MASE_fold6  0.59742
6    MASE_fold7  0.58059
7    MASE_fold8  0.56822
8    MASE_fold9  0.54768
9   MASE_fold10  0.56808
10      Average  0.61037

# Final Prediction

In [188]:
y9 = train1[(train1['week'] >= 134) & (train1['week'] <= 143)]
test_actual9 = y9[['num_orders']]
y9 = y9.drop(['id', 'num_orders'], axis=1)

test_final = df_train[df_train['week'] >= 146].copy()
x_test_final = test_final.drop(['id', 'num_orders'], axis=1)
y_test_final = test_final['num_orders'] 

In [189]:
DecisionTreeRegModel.fit(y9,test_actual9)
y_pred_final = DecisionTreeRegModel.predict(x_test_final)
final_num_orders = pd.DataFrame({'Actual':y_test_final, 'Predicted':y_pred_final})
final_num_orders

Actual  Predicted
456548     0.0      202.0
456549     0.0      189.0
456550     0.0      189.0
456551     0.0       41.0
456552     0.0       67.0
...        ...        ...
489116     0.0       95.0
489117     0.0       53.0
489118     0.0      391.0
489119     0.0      269.0
489120     0.0      204.0

[32573 rows x 2 columns]

In [190]:
final_num_orders.to_csv('num_orders.csv')